openapi: 3.0.3
info:
  version: 1.0.0
  title: Financier API
  description: OpenAPI specification of the Financier service
  contact:
    name: Financier developer
    email: olegshishkin@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /
paths:
  /api/v1/accounts:
    get:
      tags:
        - Accounts
      description: Returns all accounts.
      operationId: getAllAccounts
      parameters: [ ]
      responses:
        '200':
          description: account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Accounts
      description: Creates new account.
      operationId: addAccount
      requestBody:
        description: Account to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccountInput'
      responses:
        '201':
          description: account creation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/accounts/{id}:
    get:
      tags:
        - Accounts
      description: Returns an account by its ID.
      operationId: findAccountByID
      parameters:
        - name: id
          in: path
          description: ID of account to fetch
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        '200':
          description: account response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountOutput'
        '404':
          description: no account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ID:
      description: Object unique identifier.
      type: string
      nullable: false
      minLength: 1
      maxLength: 36
      example: 123
      x-oapi-codegen-extra-tags:
        binding: "required,min=1,max=36"
    Version:
      description: Object version. Used for optimistic locking.
      type: string
      format: uint64
      minimum: 0
      example: 16
      x-oapi-codegen-extra-tags:
        binding: "required,numeric,gte=0"
    NewAccountInput:
      description: Input for a new account creation.
      type: object
      properties:
        name:
          description: Account name.
          type: string
          nullable: false
          minLength: 1
          maxLength: 255
          example: wallet
          x-oapi-codegen-extra-tags:
            binding: "required,min=1,max=255"
        comment:
          description: Account comment.
          type: string
          minLength: 0
          maxLength: 255
          example: My new account
          x-oapi-codegen-extra-tags:
            binding: "omitempty,min=0,max=255"
      required:
        - name
      additionalProperties: false
    AccountOutput:
      description: Account.
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ID'
          required:
            - id
          additionalProperties: false
        - $ref: '#/components/schemas/NewAccountInput'
        - type: object
          properties:
            balance:
              description: |
                Current account balance. The balance is represented by an integer to ensure accuracy. \
                To determine the real balance, you need to divide the current number by 100.
              type: integer
              format: int64
              minimum: 0
              example: 1203
              x-oapi-codegen-extra-tags:
                binding: "required,numeric"
            disabled:
              description: Account activity status.
              type: boolean
              example: true
              x-oapi-codegen-extra-tags:
                binding: "required,boolean"
          required:
            - balance
            - disabled
          additionalProperties: false
        - type: object
          properties:
            version:
              $ref: '#/components/schemas/Version'
          required:
            - version
          additionalProperties: false
    Error:
      description: Error structure.
      type: object
      properties:
        code:
          description: Error code.
          type: integer
          format: int8
          minimum: 0
          maximum: 127
          example: 1
          x-oapi-codegen-extra-tags:
            binding: "required,numeric,gte=0,lte=127"
        message:
          description: Error message.
          type: string
          nullable: false
          minLength: 1
          maxLength: 4000
          example: Unexpected error
          x-oapi-codegen-extra-tags:
            binding: "required,min=1,max=4000"
      required:
        - code
        - message
      additionalProperties: false